package simabi

import (
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func TestRender(t *testing.T) {
	header := filepath.Join(t.TempDir(), "SDK with spaces", "C_API", "pd_api.h")
	sources, err := Render(Config{
		APIHeader:         header,
		RuntimeImport:     "github.com/Djunichi/gopdsdk/internal/features/runtime",
		PlaydateImport:    "github.com/Djunichi/gopdsdk/playdate",
		ApplicationImport: "github.com/Djunichi/gopdsdk/probe/app",
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"#include " + strconv.Quote(filepath.ToSlash(header)),
		`github.com/Djunichi/gopdsdk/probe/app`,
		"sdkRuntime.NewApplication(app.New(), gameContext",
		"application.Handle",
		"application.Update",
		"sdkPlaydate.Buttons(C.bridgeButtons())",
		"C.bridgeCrankAngle",
		"C.bridgeCrankDelta",
		"C.bridgeCrankDocked",
		"C.bridgeFrameDelta",
		"C.bridgeClear",
		"C.bridgeDrawText",
		"C.bridgeLoadFont",
		"C.bridgeTextWidth",
		"C.bridgeFontHeight",
		"C.bridgeFreeFont",
		"C.bridgeCurrentTimeMilliseconds",
		"C.bridgeExitToLauncher",
		"C.bridgeSetAccelerometerEnabled",
		"C.bridgeAccelerometer",
		"C.bridgePowerStatus",
		"C.bridgeBatteryPercentage",
		"C.bridgeSystemVolume",
		"C.bridgeTimezoneOffsetSeconds",
		"sdkPlaydate.FileSystem",
		"sdkPlaydate.SystemMenu",
		"sdkPlaydate.Localization",
		"sdkPlaydate.Scoreboards",
		"sdkPlaydate.DebugMessages",
		"goSerialMessage",
		"goScoreCallback",
		"sdkRuntime.NewScoreboardService",
		"C.bridgeGetScores",
		"goMenuCallback",
		"bridgeLocalizedText",
		"C.bridgeFree",
		"sdkRuntime.NewOwnedFile",
		"C.bridgeFileOpen",
		"C.bridgeFileList",
		"C.bridgeFileRename",
		"C.bridgeLoadBitmap",
		"C.bridgeLoadBitmapTable",
		"C.bridgeBitmapTableFrame",
		"C.bridgeFreeBitmapTable",
		"C.bridgeNewBitmap",
		"C.bridgeFreeBitmap",
		"C.bridgeBitmapSize",
		"C.bridgeFillBitmap",
		"C.bridgeBitmapData",
		"C.bridgeCopyBitmap",
		"C.bridgeLoadIntoBitmap",
		"C.bridgeNewBitmapTable",
		"C.bridgeLoadIntoBitmapTable",
		"C.bridgeSetBitmapMask",
		"C.bridgeGetBitmapMask",
		"C.bridgeCheckMaskCollision",
		"C.bridgeRotatedBitmap",
		"C.bridgeCopyDisplayBuffer",
		"C.bridgeDrawBitmap",
		"C.bridgeDrawScaledBitmap",
		"C.bridgeDrawRotatedBitmap",
		"C.bridgeSetStencil",
		"C.bridgeClearStencil",
		"C.bridgeLoadVideo",
		"C.bridgeVideoRenderFrame",
		"sdkRuntime.NewVideoPlayer",
		"C.bridgeDisplaySetRefreshRate",
		"C.bridgeDisplaySetScale",
		"C.bridgeDisplaySetMosaic",
		"C.bridgeDrawLine",
		"C.bridgeDrawEllipse",
		"C.bridgeSetClipRect",
		"C.bridgeSetDrawMode",
		"C.bridgeFillPolygon",
		"C.bridgeDrawRoundedRect",
		"C.bridgeFillRoundedRect",
		"C.bridgeSetLineCapStyle",
		"C.bridgeSetBackgroundColor",
		"C.bridgeSetScreenClipRect",
		"C.bridgeGetFrame",
		"C.bridgeMarkUpdatedRows",
		"sdkRuntime.WithFramebuffer",
		"sdkRuntime.OwnedBitmapHandle",
		"C.bridgePushContext",
		"C.bridgePopContext",
		"C.bridgeNewSprite",
		"C.bridgeSpriteSetBitmap",
		"C.bridgeSpriteMoveTo",
		"C.bridgeSpriteMoveBy",
		"C.bridgeSpriteSetVisible",
		"C.bridgeSpriteSetZIndex",
		"C.bridgeSpriteSetCollideRect",
		"C.bridgeSpriteMarkDirty",
		"C.bridgeSpriteMarkDirtyRect",
		"C.bridgeSpriteMoveWithCollisions",
		"C.bridgeQuerySpritesAtPoint",
		"C.bridgeQuerySpritesInRect",
		"C.bridgeSpriteAdd",
		"C.bridgeSpriteRemove",
		"C.bridgeSetAlwaysRedraw",
		"C.bridgeAddDirtyRect",
		"C.bridgeFreeSprite",
		"C.bridgeUpdateAndDrawSprites",
		"C.bridgeLoadSoundEffect",
		"C.bridgeSamplePlayerPlay",
		"C.bridgeLoadFilePlayer",
		"C.bridgeFilePlayerSetRate",
		"C.bridgeCurrentAudioTime",
		"C.bridgeSoundEffectSetFinishCallback",
		"C.bridgeFilePlayerFadeVolume",
		"sdkRuntime.InvokeAudioCallback",
		"sdkRuntime.NewSoundEffect",
		"sdkRuntime.NewSamplePlayer",
		"sdkPlaydate.PCMPlayers",
		"C.bridgeNewPCMPlayer",
		"sdkRuntime.NewFilePlayer",
		"sdkRuntime.NewAudioChannel",
		"sdkRuntime.NewSynth",
		"sdkRuntime.NewLFO",
		"sdkRuntime.NewEnvelope",
		"sdkRuntime.NewControlSignal",
		"sdkPlaydate.Microphones",
		"sdkRuntime.NewMicrophoneService",
		"goMicrophonePermission",
		"goMicrophoneSamples",
	} {
		if !strings.Contains(sources.Go, want) {
			t.Errorf("Go source does not contain %q:\n%s", want, sources.Go)
		}
	}
	for _, want := range []string{
		"#include " + strconv.Quote(filepath.ToSlash(header)),
		"setUpdateCallback(bridgeUpdate, NULL)",
		"setSerialMessageCallback(bridgeSerialMessage)",
		"scoreboards->addScore",
		"scoreboards->getPersonalBest",
		"scoreboards->getScoreboards",
		"scoreboards->getScores",
		"scoreboards->freeScoresList",
		"graphics->clear(kColorWhite)",
		"drawText(text, length, kUTF8Encoding, x, y)",
		"graphics->loadFont",
		"graphics->getTextWidth",
		"graphics->getFontHeight",
		"graphics->setTextTracking",
		"graphics->getTextTracking",
		"graphics->setTextLeading",
		"graphics->drawTextInRect",
		"graphics->getTextHeightForMaxWidth",
		"graphics->getFontPage",
		"graphics->getPageGlyph",
		"graphics->getGlyphKerning",
		"system->realloc((void*)font, 0)",
		"system->getCurrentTimeMilliseconds()",
		"sound->getCurrentTime()",
		"sound->channel->newChannel",
		"sound->synth->newSynth",
		"sound->lfo->newLFO",
		"sound->envelope->newEnvelope",
		"sound->controlsignal->newSignal",
		"sound->requestMicAccess",
		"sound->setMicCallback",
		"fileplayer->fadeVolume",
		"sampleplayer->setFinishCallback",
		"sample->newSampleFromData",
		"system->exitToLauncher()",
		"file->open",
		"file->read",
		"file->listfiles",
		"file->rename",
		"system->getButtonState",
		"system->getCrankAngle",
		"system->getCrankChange",
		"system->isCrankDocked",
		"system->getElapsedTime",
		"system->resetElapsedTime",
		"graphics->loadBitmap",
		"graphics->loadBitmapTable",
		"graphics->getTableBitmap",
		"graphics->freeBitmapTable",
		"graphics->newBitmap",
		"graphics->freeBitmap",
		"graphics->getBitmapData",
		"graphics->clearBitmap",
		"graphics->copyBitmap",
		"graphics->loadIntoBitmap",
		"graphics->newBitmapTable",
		"graphics->loadIntoBitmapTable",
		"graphics->setBitmapMask",
		"graphics->getBitmapMask",
		"graphics->checkMaskCollision",
		"graphics->rotatedBitmap",
		"graphics->copyFrameBufferBitmap",
		"graphics->drawBitmap",
		"graphics->drawScaledBitmap",
		"graphics->drawRotatedBitmap",
		"graphics->setStencilImage",
		"graphics->setStencil(NULL)",
		"graphics->drawLine",
		"graphics->fillTriangle",
		"graphics->setClipRect",
		"graphics->setDrawMode",
		"graphics->fillPolygon",
		"graphics->drawRoundRect",
		"graphics->fillRoundRect",
		"graphics->setLineCapStyle",
		"graphics->setBackgroundColor",
		"graphics->setScreenClipRect",
		"graphics->getFrame",
		"graphics->markUpdatedRows",
		"graphics->pushContext",
		"graphics->popContext",
		"display->setRefreshRate",
		"display->setScale",
		"display->setMosaic",
		"sprite->newSprite",
		"sprite->setImage",
		"sprite->moveTo",
		"sprite->moveBy",
		"sprite->setVisible",
		"sprite->setZIndex",
		"sprite->setCollideRect",
		"sprite->markDirty",
		"sprite->markDirtyRect",
		"sprite->moveWithCollisions",
		"sprite->querySpritesAtPoint",
		"sprite->querySpritesInRect",
		"sprite->addSprite",
		"sprite->removeSprite",
		"sprite->setAlwaysRedraw",
		"sprite->addDirtyRect",
		"LCDMakeRect",
		"sprite->freeSprite",
		"sprite->updateAndDrawSprites",
		"sound->sample->load",
		"sound->sampleplayer->newPlayer",
		"graphics->video->loadVideo",
		"graphics->video->renderFrame",
		"sound->fileplayer->loadIntoPlayer",
	} {
		if !strings.Contains(sources.C, want) {
			t.Errorf("C source does not contain %q:\n%s", want, sources.C)
		}
	}
}

func TestRenderRequiresEveryInput(t *testing.T) {
	_, err := Render(Config{})
	if got, want := err.Error(), "render Simulator ABI: APIHeader is required"; got != want {
		t.Fatalf("Render() error = %q, want %q", got, want)
	}
}
